# Base configs
baseurl: "https://photos.joshwinton.com 
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Josh Winton"
subtitle: "Some of the neat things I've seen 😄"
author: "Josh Winton"
header:
 title: "Photography"
 subtitle: "by Josh Winton"
footer:
 name: "Hey there, my name is Josh"
 bio: ""
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork this repo on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: ""
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: ""
